### ISSUE TITLE
Daemon confused about net

### ISSUE THREAD

**Issue by mikalv** [Anoncoin/anoncoin#13]
Seems like the testnet node tries to contact mainnet nodes. This has to be fixed.

**Comment by yhaenggi** [comment]
Thats protocol basics ;)
pchMessageStart should never be the same for testnet and clearnet. It contains the magic bytes which are sent when connecting.

**Comment by mikalv** [comment]
Yes I'm well known with the magic bytes, however seems some maintainer wasn't while I was gone. I'm going to patch this in front of next release.

**Comment by mikalv** [comment]
However the code says that mainnet pchMessageStart != testnet pchMessageStart. I think it's issues around the addressbook and port of choise.

**Comment by GroundRod** [comment]
Can we close this topic now?

**Comment by mikalv** [comment]
Lets do it, if problem still occurs, we can reopen.
