### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by Choms** [Anoncoin/anoncoin#28]
Hi, the website is down for quite a while now, can someone fix it or transfer ownership of the project over to someone who can maintain it? thanks

**Comment by GroundRod** [comment]
Hay Choms, have had the same thought for sometime too.

Been along while since I was active, just as well start by seeing if I can get any answer from someone on the team regarding this, will post back here to let you and others know what, if anything I've found out....

**Comment by ghbjklhv** [comment]
I tried visiting the site today.
Site is definitely down: https://archive.fo/QtOJy

**Comment by GroundRod** [comment]
Ok Anoncoin.net has been restored via my dns, check it on your end now please.

Expect additional delays as content changes are in the works, right now the download link page comes up for most menu tabs when moused, providing new users with what is needed to join our community.  The many different platform executables.

The important point right now is the site is back.

As to the websites functionality I think what is Important to the project & team right now, is scrub staleness... plus bring forward new content that explains some of the cool features that the Anoncoin Ecosystem cranks out every 3 minutes blocks for...

Decisions regarding the block explorer website fate is not known to me, will pass on what I learn and leave this issue open for discussion of that topic, now that the Anoncoin.net site is back up.
 
Peace out,

GR

**Comment by mikalv** [comment]
Hi GroundRod, welcome back. I've got the website both on i2p and clearnet visible again, sorry for the downtime. Some teammembers couldn't contribute anymore and I had to move DNS and web back to my servers.
