### ISSUE TITLE
Release roadmap for 0.9.7

### ISSUE THREAD

**Issue by mikalv** [Anoncoin/anoncoin#3]
# Release roadmap for 0.9.7

* New DNS Seeds
* CMake build system (finally trashing autotools)
* Minor bugfixes and improvements
* Add new alert key?

**Comment by oyvkva** [comment]
Put draft for full roadmap here: https://github.com/Anoncoin/project/tree/master/roadmap

**Comment by bangmac** [comment]
good for comeback :)

**Comment by GroundRod** [comment]
Topic here seems stale to me, a current roadmap would be appreciated though.
